version: "3.9"

services:

  football_container:
    container_name: football_container
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=football_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/football-data2

volumes:
  node_db_data: {}